// Code generated by "stringer -type=Token"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RIGHT-0]
	_ = x[LEFT-1]
	_ = x[DOWN-2]
	_ = x[UP-3]
	_ = x[MIRFORWARD-4]
	_ = x[MIRBACKWARD-5]
	_ = x[MIRVERTICAL-6]
	_ = x[MIRHORIZONTAL-7]
	_ = x[MIRREVERSE-8]
	_ = x[RANDOM-9]
	_ = x[SKIP-10]
	_ = x[SKIPIF-11]
	_ = x[JUMP-12]
	_ = x[VAL-13]
	_ = x[ADD-14]
	_ = x[SUB-15]
	_ = x[MUL-16]
	_ = x[DIV-17]
	_ = x[MOD-18]
	_ = x[EQ-19]
	_ = x[DUPLICATE-20]
	_ = x[REMOVE-21]
	_ = x[SWAP-22]
	_ = x[TOPSHIFT-23]
	_ = x[RSHIFT-24]
	_ = x[LSHIFT-25]
	_ = x[REVERSE-26]
	_ = x[LENGTH-27]
	_ = x[NEW-28]
	_ = x[CONSUME-29]
	_ = x[OCHAR-30]
	_ = x[ONUM-31]
	_ = x[READ-32]
	_ = x[REGISTER-33]
	_ = x[PEEK-34]
	_ = x[POKE-35]
	_ = x[HALT-36]
	_ = x[WHITESPACE-37]
	_ = x[EOF-38]
}

const _Token_name = "RIGHTLEFTDOWNUPMIRFORWARDMIRBACKWARDMIRVERTICALMIRHORIZONTALMIRREVERSERANDOMSKIPSKIPIFJUMPVALADDSUBMULDIVMODEQDUPLICATEREMOVESWAPTOPSHIFTRSHIFTLSHIFTREVERSELENGTHNEWCONSUMEOCHARONUMREADREGISTERPEEKPOKEHALTWHITESPACEEOF"

var _Token_index = [...]uint8{0, 5, 9, 13, 15, 25, 36, 47, 60, 70, 76, 80, 86, 90, 93, 96, 99, 102, 105, 108, 110, 119, 125, 129, 137, 143, 149, 156, 162, 165, 172, 177, 181, 185, 193, 197, 201, 205, 215, 218}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
