// Code generated by "stringer -type=Token"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RIGHT-0]
	_ = x[LEFT-1]
	_ = x[DOWN-2]
	_ = x[UP-3]
	_ = x[MIRFORWARD-4]
	_ = x[MIRBACKWARD-5]
	_ = x[MIRVERTICAL-6]
	_ = x[MIRHORIZONTAL-7]
	_ = x[MIRREVERSE-8]
	_ = x[RANDOM-9]
	_ = x[SKIP-10]
	_ = x[SKIPIF-11]
	_ = x[JUMP-12]
	_ = x[VAL-13]
	_ = x[ADD-14]
	_ = x[SUB-15]
	_ = x[MUL-16]
	_ = x[DIV-17]
	_ = x[MOD-18]
	_ = x[EQ-19]
	_ = x[LT-20]
	_ = x[GT-21]
	_ = x[QUOTE-22]
}

const _Token_name = "RIGHTLEFTDOWNUPMIRFORWARDMIRBACKWARDMIRVERTICALMIRHORIZONTALMIRREVERSERANDOMSKIPSKIPIFJUMPVALADDSUBMULDIVMODEQLTGTQUOTE"

var _Token_index = [...]uint8{0, 5, 9, 13, 15, 25, 36, 47, 60, 70, 76, 80, 86, 90, 93, 96, 99, 102, 105, 108, 110, 112, 114, 119}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
